
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In dbt, the default materialization for a model is a view. This means, when you run 
# dbt run or dbt build, all of your models will be built as a view in your data platform. 
# The configuration below will override this setting for models in the example folder to 
# instead be materialized as tables. Any models you add to the root of the models folder will 
# continue to be built as views. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.

models:
  my_new_project:
    pre-hook:
      - "GRANT ALL ON schema {{ schema }} to ROLE test_role;"
      - "insert into qwt_audit.qwt_audit_info values( '{{ this }}', current_timestamp(),Null,Null)"
    post-hook:
      - "update qwt_audit.qwt_audit_info set end_time = current_timestamp(), duration = datediff('second',start_time,current_timestamp()) where modelname = '{{this}}'"

    # Applies to all files under models/example/
    staging:
      +materialized: table
    transform:
      +materialized: table
      +schema: transform

on-run-start: 
  - "GRANT ALL ON DATABASE QWT_ANALYTICS to ROLE test_role;"
  - "GRANT ALL ON ALL TABLES IN SCHEMA QWT_ANALYTICS.DBT_DEV to ROLE test_role;"
# on-run-end: "{{ dbt_artifacts.upload_results(results) }}"

vars:
  city: 'paris'